### ISSUE TITLE
image not getting loaded

### ISSUE THREAD

**Issue by Prudhvinik1** [yikang-li/FactorizableNet#24]
/home/prudhvik/FactorNet/FactorizableNet/data/VRD/images/sg_test_images/161638840_4de67b36c9_o.jpg
    use_gt_boxes=args.use_gt_boxes)
  File "/home/prudhvik/FactorNet/FactorizableNet/models/HDN_v2/engines_v1.py", line 123, in test
    for i, sample in enumerate(loader): # (im_data, im_info, gt_objects, gt_relationships)
  File "/home/prudhvik/anaconda/envs/py2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/prudhvik/anaconda/envs/py2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/prudhvik/anaconda/envs/py2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/prudhvik/FactorNet/FactorizableNet/lib/datasets/VRD_loader.py", line 66, in __getitem__
    img_original_shape = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

Hi, I see that some of the images are not being read by imread() function and causing this issue. I am using VRD dataset for evaluating the pretrained model.

**Comment by varshanth** [comment]
Same issue. @yikang-li , can you please let us know the fix?

**Comment by yikang-li** [comment]
Can you please provide the OpenCV version?

Did you use the dataset we provided?

**Comment by Hastyrush** [comment]
Hi @Prudhvinik1,

You should check if your symbolic link **(ln -s /path/to/images F-Net/data/VRD/images)** is done properly. The error means that the loader cannot find the specified folder to load the images from.

 I encountered this problem as well, and I solved it by setting the correct link path to the image folder. Hope this helps!

**Comment by muraliadithya** [comment]
@yikang-li @Hastyrush I am having similar problems. I have the following questions:
(i) I am currently using the VRD dataset using the link provided. It extracts to a folder called sg_dataset with two jsons and two other folders full of images inside it (one each for traning and testing images). Where should I put this, relative to the repository?
(ii) What should the /path/to/images symlink point to?
(iii) Once this issue clears up, where can I find predictions for the images, and if possible, how can I query the model on new images that I have?

Thanks a lot!

**Comment by mkt1412** [comment]
> @yikang-li @Hastyrush I am having similar problems. I have the following questions:
> (i) I am currently using the VRD dataset using the link provided. It extracts to a folder called sg_dataset with two jsons and two other folders full of images inside it (one each for traning and testing images). Where should I put this, relative to the repository?
> (ii) What should the /path/to/images symlink point to?
> (iii) Once this issue clears up, where can I find predictions for the images, and if possible, how can I query the model on new images that I have?
> 
> Thanks a lot!

Hi, I'm facing the same problem. Have you got it resolved? Thanks!

**Comment by brleandro** [comment]
I am having the same problem with the image data/VRD/images/sg_test_images/9535248286_31dee34cdf_b.jpg.

Does anyone know how to solve?
