### ISSUE TITLE
when evaluate_object,error occured

### ISSUE THREAD

**Issue by sometimething** [yikang-li/FactorizableNet#33]
the order is 
CUDA_VISIBLE_DEVICES=0 python train_FN.py --evaluate_object \
	--path_opt options/models/VRD.yaml \
	--pretrained_model output/best_model_4.h5
========== Testing =======
============ Done ============
Done dumping to: output/FN_VRD_2_iters_SGD/evaluate_object_detection
Evaluating...
Traceback (most recent call last):
  File "train_FN.py", line 402, in <module>
    main()
  File "train_FN.py", line 299, in main
    python_eval(path_dets, osp.join(data_opts['dir'], 'object_xml'))
NameError: global name 'python_eval' is not defined.
How to deal with this problem?Thanks!

**Comment by mkt1412** [comment]
Im having the same problem, have you solved it already. The function "python-eval" seems to be missing.
