### ISSUE TITLE
Missing Function "python_eval"

### ISSUE THREAD

**Issue by mkt1412** [yikang-li/FactorizableNet#42]
Hi,

Thanks for publicizing the code and it is really well-written. However, there seems to a minor prpblem related to evaluating object detection result.  In train_FN.py, there is no reference for function "python_eval"  as shown below:

`if args.evaluate_object:`
 `result = model.module.engines.test_object_detection(test_loader, model, nms=args.nms,use_gt_boxes=args.use_gt_boxes)`
 `print('============ Done ============')`
  `path_dets = save_detections(result, None, options['logs']['dir_logs'], is_testing=True)`
  `print('Evaluating...')`
 `python_eval(path_dets, osp.join(data_opts['dir'], 'object_xml'))`
 ` return` 

Would it possible to upload the code for this function? Thanks in advance

**Comment by minghehe-nobug** [comment]
hello, I have a question which seems earlier before yours
I can't config the file named eval and have no idea where is the module "eval.evaluator"
maybe you can help me out
and sorry about can't answer your question
Thanks

**Comment by mkt1412** [comment]
> hello, I have a question which seems earlier before yours
> I can't config the file named eval and have no idea where is the module "eval.evaluator"
> maybe you can help me out
> and sorry about can't answer your question
> Thanks

Hi, can you give more details on which part or file or code line you are having problem with?

**Comment by minghehe-nobug** [comment]
Well I have already compiled the project and downloaded the module
When I prepare the datasets I run "python visualize_graph.py" to see how it works
it turns out the following error
"
Traceback (most recent call last):
  File "visualize_graph.py", line 25, in <module>
    from eval.evaluator import DenseCaptioningEvaluator
ImportError: No module named eval.evaluator
"
I have already run "./scripts/setup_eval.sh" and the file "eval" is in the same file with "visualize_graph.py"
however there is no "evaluator" in eval, no module named eval.evaluator

I'm a beginner in git and maybe have some stupid questions, but really appreciate.

**Comment by mkt1412** [comment]
> Well I have already compiled the project and downloaded the module
> When I prepare the datasets I run "python visualize_graph.py" to see how it works
> it turns out the following error
> "
> Traceback (most recent call last):
> File "visualize_graph.py", line 25, in
> from eval.evaluator import DenseCaptioningEvaluator
> ImportError: No module named eval.evaluator
> "
> I have already run "./scripts/setup_eval.sh" and the file "eval" is in the same file with "visualize_graph.py"
> however there is no "evaluator" in eval, no module named eval.evaluator
> 
> I'm a beginner in git and maybe have some stupid questions, but really appreciate.

Thanks for the detailed description. For my own situation, I simply commented that line since 'DenseCaptioningEvaluator' is not called. You should be able to run 'visualize_graph.py' properly then.

**Comment by minghehe-nobug** [comment]
Thanks a lot for your help!
After training and testing, I can finally get a correct model and successfully evaluate the datasets
The file visuallize_graph.py works as well
Tks

**Comment by mkt1412** [comment]
> Thanks a lot for your help!
> After training and testing, I can finally get a correct model and successfully evaluate the datasets
> The file visuallize_graph.py works as well
> Tks

My pleasure.
